-- An event / club event / series now carries its own activity type
-- (run, trail_run, walk, hike, bike) instead of being implicitly whatever
-- its route is — a hosted "trail run on this loop" reads differently from a
-- "hike on this loop". Backfilled from the linked route.

alter table public.group_runs
  add column if not exists activity_type text not null default 'run'
    check (activity_type in ('run', 'trail_run', 'hike', 'bike', 'walk', 'other'));

update public.group_runs g
set activity_type = coalesce(r.activity_type, 'run')
from public.routes r
where r.id = g.route_id;

alter table public.recurring_series
  add column if not exists activity_type text not null default 'run'
    check (activity_type in ('run', 'trail_run', 'hike', 'bike', 'walk', 'other'));

update public.recurring_series s
set activity_type = coalesce(r.activity_type, 'run')
from public.routes r
where r.id = s.route_id;

-- Occurrences generated by 0029 don't set activity_type/visibility; the
-- 0066 trigger already backfills visibility from the series — extend it to
-- carry activity_type too.
create or replace function public.set_group_run_visibility_from_series()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.series_id is not null then
    select
      coalesce(visibility, 'public'),
      coalesce(activity_type, 'run')
    into new.visibility, new.activity_type
    from public.recurring_series where id = new.series_id;
  end if;
  return new;
end;
$$;
